site_name: NeonAIÂ® Documentation
site_url: https://neongeckocom.github.io/neon-docs
theme: readthedocs

nav:
  - About: index.md
  - Overview:
    - Definitions: overview/definitions
    - Frequently Asked Questions: overview/faq
  - Neon Core:
    - Introduction: neon_core/index.md
    - Quick Start: neon_core/quick_start.md
    - Core Modules:
      - Introduction: neon_core/index.md
      - Messagebus: neon_core/neon_messagebus.md
      - Speech: neon_core/neon_speech.md
      - Audio: neon_core/neon_audio.md
      - Skills: neon_core/neon_skills.md
      - GUI: neon_core/neon_gui.md
      - Enclosure: neon_core/neon_enclosure.md
  - Neon OS:
    - Introduction: neon_os/index.md
    - Installation: neon_os/neon_os_installation.md
    - Using Neon OS: neon_os/using_neon_os.md
    - Updating: neon_os/neon_os_updates.md
    - Neon OS on the Mark II: neon_os/On_the_MarkII.md
    - Debos Base Images: neon_os/neon_debos.md
    - Neon Image Recipes: neon_os/neon_image_recipe.md
    - Tips: neon_os/tips.md
  - Quick Reference Guides:
    - Terminal: quick_reference/terminal.md
    - Logs: quick_reference/logging.md
    - Configuration: quick_reference/configuration.md
    - Installing Skills: quick_reference/installing_skills.md
    - Installing Plugins: quick_reference/installing_plugins.md
  - Developer References:
      - Working with Git(Hub): developers/git_overview.md
      - skill.json: developers/skill_json.md
  - Skill Development:
      - Adapt Intents: skill_development/adapt_intents.md
      - Padatious Intents: skill_development/padatious_intents.md
      - Testing: skill_development/skill_testing.md
